#!/bin/bash

# docker run --name sparklet-blog --volume="$PWD:/srv/jekyll" -p 3000:4000 -it jekyll/jekyll bundle install bundle exec jekyll build
docker run -p 4000:4000 -v "$(pwd)":/site bretfisher/jekyll-serve
